name: Download and Run JAR from JFrog Artifactory

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        
jobs:
  download-and-run-jar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download JAR
      run: |
        ARTIFACTORY_URL="http://3.135.1.139:8081/artifactory"
        REPO_KEY="my-maven-local-releases"
        GROUP_ID="com/example"
        ARTIFACT_ID="my-java-app"
        VERSION="1.0.0"
        FILENAME="my-java-app-${VERSION}.jar"
        
        curl -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_PASSWORD }} -O \
          "$ARTIFACTORY_URL/$REPO_KEY/$GROUP_ID/$ARTIFACT_ID/$VERSION/$FILENAME"

    - name: Run JAR
      run: java -jar $GITHUB_WORKSPACE/$FILENAME      