name: Java CI/CD with Maven, Artifactory, and GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Create .m2 directory
      run: mkdir -p $HOME/.m2

    - name: Copy settings.xml
      run: cp .github/settings.xml $HOME/.m2/settings.xml

    - name: Publish to Artifactory
      run: mvn deploy
